<?php

// autoload.php @generated by Composer
//var_dump(__DIR__);
//D:\PHPSTUDY\PHPTutorial\WWW\framework\src
//var_dump(__DIR__ . '../vendor/composer/autoload_real.php');
//D:\PHPSTUDY\PHPTutorial\WWW\framework\src../vendor/composer/autoload_real.php

require_once __DIR__ . '/../vendor/composer/autoload_real.php';

return ComposerAutoloaderInit4f1688f710f19329e559403c1d82da9d::getLoader();
